//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.14 at 04:56:05 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "soap.soap_rest_example.acse2020.wwu.de", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.wwu.acse2020.soap_rest_example.soap;
